name: Build and deploy Python app to Azure Web App - wamsisatellite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: sudo apt-get install -y libgeos-dev

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgeos-dev

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B3E134AD8C8447AA051BE2D5D88DB7A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_287D679B7CFF4590B1882FBB794AF5C4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F01B9BC104B401DB2A04073BAC4D3DB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'wamsisatellite'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Set startup command
        run: az webapp config set --name wamsisatellite --resource-group wamsisatellite_group --startup-file 'gunicorn --bind 0.0.0.0:$PORT app:app'

      - name: Restart Azure Web App
        run: az webapp restart --name wamsisatellite --resource-group wamsisatellite_group

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write
      contents: read
