name: Deploy to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: sudo apt-get install -y libgeos-dev

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B3E134AD8C8447AA051BE2D5D88DB7A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_287D679B7CFF4590B1882FBB794AF5C4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F01B9BC104B401DB2A04073BAC4D3DB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        run: |
          az webapp up --name wamsisatellite --resource-group wamsisatellite_group --location Australia East --runtime "PYTHON|3.8"

      - name: Restart Azure Web App
        run: az webapp restart --name wamsisatellite --resource-group wamsisatellite_group

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
